site_name: "docs"
site_url: "https://ruzickahub.github.io/docs/"
site_description: "Documentation that also shines"
site_author: "Alban Siffer <31479857+asiffer@users.noreply.github.com>"
dev_addr: "127.0.0.1:8080"
repo_url: "https://github.com/RuzickaHub/docs"
theme:
  name: shadcn
  icon: null
  pygments_style:
    light: shadcn-light
    dark: github-dark
  katex_options:
    macros:
      "\\dx": "\\mathrm{d}x"
      
plugins:
  - search
  - excalidraw
  - mkdocstrings

markdown_extensions:
  admonition:
  codehilite:
  fenced_code:
  footnotes:
  extra:
  pymdownx.blocks.details:
  pymdownx.tabbed:
  pymdownx.blocks.tab:
    combine_header_slug: true
    separator: ___
  pymdownx.progressbar:
  pymdownx.snippets:
  pymdownx.arithmatex:
    generic: true
  shadcn.extensions.echarts.alpha:
  shadcn.extensions.codexec:
  shadcn.extensions.iconify:
  pymdownx.blocks.caption:
